### ISSUE TITLE
A small issue about sync

### ISSUE THREAD

**Issue by JohnSmith0602** [zhouzhuojie/meteor-vue#12]
Hi, when I use the sync attribute in Vue object like:
```javascript
var vm = new Vue({
  data: {},
  sync: {
    members: function() {
      return Members.find();
    }
  }
});
```

I got a Vue warn in console:
[Vue warn]: You are setting a non-existent path "members" on a vm instance. Consider pre-initializing the property with the "data" option for more reliable reactivity and better performance.

I can add 'members' as a property to data attribute to remove the warning. I wonder if it's the best practice? And if so, maybe it's good to be mentioned in the README.md.

Thanks!

**Comment by zhouzhuojie** [comment]
Good catch, will fix this warning next patch version. Thanks.

**Comment by JohnSmith0602** [comment]
Thanks for your maintaining. I shall keep it open, till it's fixed.

**Comment by zhongqf** [comment]
@zhouzhuojie How about this?

**Comment by JohnSmith0602** [comment]
Thanks, the warning is gone now, and the upgrade drives me switching to Vue.js 1.0. With hours of work, everything looks fine now! Many thanks.
