### ISSUE TITLE
Webpack

### ISSUE THREAD

**Issue by niallobrien** [zhouzhuojie/meteor-vue#18]
I've done some work with Meteor and Vue.js too. Perhaps we should look into using Webpack and forking FlowLayout (Blaze or React) to work with Vue.js also. That way we can remove Blaze altogether and write straight-up Vue.js SPAs.
What's your opinion on this?

**Comment by xkjyeah** [comment]
I like this idea! I much prefer Vue to Spacebars.

**Comment by niallobrien** [comment]
I have it working using Vue and Vue-Router. :)

**Comment by xkjyeah** [comment]
wait, with the Meteor reactive backend??

**Comment by niallobrien** [comment]
Yup.

**Comment by ryandeussing** [comment]
:thumbsup::thumbsup:

**Comment by zhouzhuojie** [comment]
+1, and parsing .vue support?

**Comment by niallobrien** [comment]
@zhouzhuojie Yup. I'm using Webpack to build the Vue single-page app (Vue-router with single-file components) which is in a hidden folder so Meteor doesn't try to compile it. So it's basically a regular standalone Vue.js app. It's then output to `/public` as `build.js` and all works fine, so long as you wait until the DOM is loaded before trying to use it (as `build.js` needs to be in the head of the document).

**Comment by niallobrien** [comment]
I've tried to get all of this working with https://atmospherejs.com/webpack/webpack so it'd be super-simple to setup, but it's not quite there yet.

**Comment by ryandeussing** [comment]
I'm curious to hear your opinions on the subject of page load/performance with Meteor and Vue. E.g. a `flow-router`/`FlowLayout` approach would give us `fast-render`, which seems a much less complex path to suitable performance than combining server-side rendering with Vue.

**Comment by niallobrien** [comment]
Page performance & Meteor generally don't tend to go hand in hand, lol. But I'm building Vue apps as regular SPAs, I just happen to be using Meteor on the backend too. Very similar setup to the MEAN stack really. Regarding SSR, I'd rather not have SSR and use Vue instead of using Blaze.

**Comment by ryandeussing** [comment]
I've managed to convince myself that a regular SPA will not have snappy enough page loads for my use case. That could be a totally false assumption. Thanks for making me consider that - and for the Vue/Meteor videos as well!

**Comment by niallobrien** [comment]
@ryandeussing I'd be interested to hear your use-case. Perhaps using Vue in conjunction with Blaze much like my existing videos show might be a nice middle-ground for you?

**Comment by ryandeussing** [comment]
I'm using Meteor similarly - I could use any backend for my current projects (which are content-heavy Craigslist-style directories), I'm just using Meteor b/c I'm more keen on learning it. 

I think I dislike Blaze less than you, so flow-router/Blaze/vue may well do the trick...

**Comment by niallobrien** [comment]
@ryandeussing Not entirely true, see the top question here: https://crater.io/posts/pn72NDyPzaHJKt7gn/crater-ama-meteor-development-group-10-10-at-12pm-pst
:)

**Comment by ryandeussing** [comment]
Aha, I misread your comment above ;) Noted!

**Comment by niallobrien** [comment]
This project appears to be no longer maintained, closing.
