### ISSUE TITLE
Initializer should add sync variables from prototype.

### ISSUE THREAD

**Issue by xkjyeah** [zhouzhuojie/meteor-vue#22]
I want to create a component that relies on a reactive field, e.g.:

    Vue.extend({
    sync: {
        reactive: function() { Collection.find({}); }
    }});

The _init function needs to add these sync-ed fields from the prototype

**Comment by xkjyeah** [comment]
Here's my fork to fix the issue.

https://github.com/xkjyeah/meteor-vue

**Comment by zhouzhuojie** [comment]
Thanks, looks good to me. Can you make a PR for it?
