### ISSUE TITLE
Vue's components

### ISSUE THREAD

**Issue by niallobrien** [zhouzhuojie/meteor-vue#6]
How can we use Vue Components with Meteor? Thanks.

**Comment by zhouzhuojie** [comment]
@niallobrien Thanks. I've added the instructions of components to README. Basically it's identical to Vue's component guide. http://vuejs.org/guide/components.html

**Comment by niallobrien** [comment]
Thanks. With MDG now supporting React etc., do you think we'd be able to use Vue with something like Flow Router and eliminate the use of Blaze? Possibly use Vue components much like React components. Just wondering what your thoughts are? Thanks.

**Comment by niallobrien** [comment]
I'd also be interested to know how you'd split the templates from the components and how would you approach communication between models. Thanks.

**Comment by zhouzhuojie** [comment]
@niallobrien  Thanks for the advice! :+1: 

I've mentioned about supporting `Template` level Vue binding with yyx990803 (MDG core and author of Vue.js), he said that's an interesting direction, but I probably don't know how to do it without injecting and wrapping `div` around the template.

If you want to completely replace Blaze with Vue, there is a wonderful example created by yyx990803, https://github.com/vuejs/vue-webpack-meteor-example. It uses `.client` to escape the tracking from Meteor (while maintains the good parts of Meteor, e.g. Database everywhere), and compile the Vue components using webpack.

**Comment by ZzZombo** [comment]
Please, add support for single-file components. They are much more pleasant to work with. Thanks.
