### ISSUE TITLE
Template on v-repeat

### ISSUE THREAD

**Issue by nerijunior** [zhouzhuojie/meteor-vue#8]
How can I set a template to use on a `v-repeat` like this:

```html
<ul>
  <template v-repeat="list">
    <li>{{msg}}</li>
    <li class="divider"></li>
  </template>
</ul>
```

**Comment by zhouzhuojie** [comment]
I'm sorry you can't. `template` is reserved by Meteor.

**Comment by nerijunior** [comment]
Exists some alternative?

**Comment by zhouzhuojie** [comment]
If you want to use componant, there is a great guide from office doc of Vue.js. Or you can simply use `div`, like `<div v-repeat='list'>`, and bind the data with meteor-vue `[[msg]]`

**Comment by nerijunior** [comment]
@zhouzhuojie Thanks!
