### ISSUE TITLE
How to use the vm data attribute as template helpers' parameter?

### ISSUE THREAD

**Issue by JohnSmith0602** [zhouzhuojie/meteor-vue#9]
Here's the sample code:
``` html
<span>[[name]]</span>  // It has a value.
<span>{{helper [[name]]}}</span>
```
Meteor says the syntax is wrong; yet if I use {{helper name}}, the name parameter is undefined.

What can I do then? Thanks.

**Comment by zhouzhuojie** [comment]
tl;dr You can't.

template is rendered before any vue instance, so it's literally `[[name]]` in the html when loading helper functions. What you need to do is just to adopt one, either use Blaze or Vue, try not to mix both.

**Comment by JohnSmith0602** [comment]
Thanks.
